---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(cluster)
library(caret)
```

```{r}
all2 <- read_csv("all2.csv")
```

```{r}
users_books <- all2 %>%
  group_by(`Book-Title`) %>%
  mutate(no_of_books = n()) %>%
  filter(no_of_books > 49) %>%
  filter(`Book-Rating` > 9) %>%
  select(`User-ID`, `Book-Title`)
```

```{r}
df <- data.frame(id = c(1,1,2,3,4), fruit = c("apple","pear","apple","orange","apple"))
df
df %>% mutate(i = 1) %>% spread(fruit, i, fill = 0)
```

```{r}
users_books <- users_books %>%
  unique()
books_wide <- users_books %>%
  mutate(i = 1) %>%
  spread(`Book-Title`,i,fill=0)
```

Zunächst skalieren wir die Datei:

```{r}
books_wide.scaled <- as.data.frame(scale(books_wide))
```



```{r}
wss <- (nrow(books_wide.scaled)-1)*sum(apply(books_wide.scaled,2,var))
  for (i in 2:10) wss[i] <- sum(kmeans(books_wide.scaled,
                                       centers=i)$withinss)
plot(1:10, wss, type="b", xlab="Number of Clusters",
     ylab="Within groups sum of squares")
```




```{r}
books_wide.dist <- dist(books_wide.scaled, method="euclidean")
books_wide.hc <- hclust(books_wide.dist, method = "ward.D2")
plot(books_wide.hc)
groups <- cutree(books_wide.hc, k=3) 
rect.hclust(books_wide.hc, k=3, border="red")
```

ok, da kann man nichts mehr erkennen. :( 

```{r}
books_wide.dist <- dist(books_wide.scaled, method="euclidean")
books_wide.hc <- hclust(books_wide.dist, method = "ward.D2")
plot(books_wide.hc)
groups <- cutree(books_wide.hc, k=2) 
rect.hclust(books_wide.hc, k=2, border="red")
```


# K Means Clustering




```{r}
k.means.fit <- kmeans(books_wide, 3) 
```

```{r}
k.means.fit$size
```


```{r}
clusplot(books_wide, k.means.fit$cluster, color=TRUE, shade=TRUE,
labels=4, lines=0, main="K-means cluster plot")
```


```{r}
table(books_wide$`1984`,k.means.fit$cluster)
```
